---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: healthchecker-pipeline
spec:
  params:
    - name: repository
      description: the git repo containing source code. If empty, the repository url will be found from toolchain
      default: ""
    - name: branch
      description: the branch for the git repo
      default: "master"
    - name: revision
      description: the git revision/commit for the git repo
      default: ""
    - name: pipeline-debug
      default: "0"
    - name: apikey
    - name: dev-region
    - name: dev-resource-group
    - name: slack-api-token
    - name: slack-webhook
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: healthchecker
      taskRef:
        name: healthchecker
      params:
        - name: apikey
          value: $(params.apikey)
        - name: region
          value: $(params.dev-region)
        - name: resource-group
          value: $(params.dev-resource-group)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: slack-api-token
          value: $(params.slack-api-token)
        - name: slack-webhook
          value: $(params.slack-webhook)
      workspaces:
        - name: workspace
          workspace: pipeline-ws