---
version: "2"
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  required:
    - build
    - repo
  $configuration:
     ENABLE_EXTENSIONS: true
     ENABLE_IF_ELSE: true
     EXPRESSION_MAXLENGTH: 1000
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: "healthchecker-{{timestamp}}"
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted"
slack:
    service_id: slack
    parameters:
      channel_name: ''
      api_token: ''
      team_url: ''
services:
  repo:
    service_id: githubconsolidated
    parameters:
      repo_url: $env.repository
      source_repo_url: "https://github.com/huayuenh/test"  
      type: "link"
      has_issues: false
      enable_traceability: false
      kind: ['pipeline']
  tekton-catalog-repo:
    service_id: githubconsolidated
    parameters:
      repo_url: "https://github.com/open-toolchain/tekton-catalog"
      source_repo_url: "https://github.com/open-toolchain/tekton-catalog"
      type: "link"
      has_issues: false
      enable_traceability: false
      kind: ['pipeline']
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: "{{toolchain.name}}"
      ui-pipeline: true
      type: tekton
      configuration:
        content:
          $text: pipeline_tekton.yml
        env:
          APP_REPO: repo
          REGISTRY_REGION_ID: "{{form.pipeline.parameters.registry-region}}"
          REGISTRY_NAMESPACE: "{{form.pipeline.parameters.registry-namespace}}"
          API_KEY: "{{form.pipeline.parameters.api-key}}"
          PROD_REGION_ID: "{{form.pipeline.parameters.prod-region}}"
          PROD_RESOURCE_GROUP: "{{form.pipeline.parameters.prod-resource-group}}"
          APP_REPO_FULL: >
            if ( $env.source_provider === 'githubconsolidated' ) {
              "https://github.com/{{services.repo.parameters.owner_id}}/{{services.repo.parameters.repo_name}}";
            } else if ( $env.source_provider === 'hostedgit' && $env.env_id === 'ibm:yp:au-syd' ) {
              "https://au-syd.git.cloud.ibm.com/{{services.repo.parameters.owner_id}}/{{services.repo.parameters.repo_name}}"
            } else if ( $env.source_provider === 'gitlab' ) {
              "https://gitlab.com/{{services.repo.parameters.owner_id}}/{{services.repo.parameters.repo_name}}";
            } else if ( $env.source_provider === 'bitbucketgit' ) {
              "https://bitbucket.org/{{services.repo.parameters.owner_id}}/{{services.repo.parameters.repo_name}}";
            } else if ( $env.source_provider === 'github_integrated' ) {
              "https://github.ibm.com/{{services.repo.parameters.owner_id}}/{{services.repo.parameters.repo_name}}";
            } else {
              "https://us-south.git.cloud.ibm.com/{{services.repo.parameters.owner_id}}/{{services.repo.parameters.repo_name}}"
            }
          PIPELINE_REPO: repo
          PIPELINE_REPO_BRANCH: >
            $env.branch ? $env.branch : "master"
          TEKTON_CATALOG_REPO: tekton-catalog-repo
          GIT_COMMIT_EVENT_LISTENER_NAME: >
            if ( $env.source_provider === 'githubconsolidated' ) {
              'github-commit';
            } else if ( $env.source_provider === 'gitlab' ) {
              'grit-or-gitlab-commit';
            } else if ( $env.source_provider === 'bitbucketgit' ) {
              'bitbucket-commit';
            } else if ( $env.source_provider === 'github_integrated' ) {
              'github-commit';
            } else {
              'grit-or-gitlab-commit';
            }
        execute: false
form:
  pipeline:
    parameters:
      prod-cluster-namespace: prod
    schema:
      $ref: deploy.json
